let foodMenus = [
  {
    "goodsNum": "20000294",
    "goodsName": "5.17晚餐",
    "goodsPrice": null,
    "goodsDesc": null,
    "goodsImg": null,
    "goodsOrder": 99,
    "canteenNum": "SZ0003",
    "canteenName": "虎踞路食堂",
    "goodsType": "CPU",
    "extAttr1": "文字列表",
    "extAttr2": "20210517",
    "extAttr3": "晚餐",
    "extAttr4": null,
    "extAttr": null,
    "goodsCategoryList": [
      {
        "goodsNum": "c4193",
        "goodsName": "熏鱼面",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      }
    ]
  },
  {
    "goodsNum": "20000282",
    "goodsName": "5.17早餐",
    "goodsPrice": null,
    "goodsDesc": null,
    "goodsImg": null,
    "goodsOrder": 99,
    "canteenNum": "SZ0003",
    "canteenName": "虎踞路食堂",
    "goodsType": "CPU",
    "extAttr1": "文字列表",
    "extAttr2": "20210517",
    "extAttr3": "早餐",
    "extAttr4": null,
    "extAttr": null,
    "goodsCategoryList": [
      {
        "goodsNum": "c28987",
        "goodsName": "巧克力曲奇",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c4860",
        "goodsName": "全麦面包",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c58531",
        "goodsName": "流沙包",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c37405",
        "goodsName": "红糖发糕",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c36715",
        "goodsName": "烤肠",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c3856",
        "goodsName": "鲜肉包",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c57606",
        "goodsName": "鸡蛋",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c30103",
        "goodsName": "豆腐脑",
        "goodsPrice": "0.5",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c30101",
        "goodsName": "蛋炒饭",
        "goodsPrice": "0.5",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c3855",
        "goodsName": "葱油饼",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      }
    ]
  },
  {
    "goodsNum": "20000284",
    "goodsName": "5.17中餐",
    "goodsPrice": null,
    "goodsDesc": null,
    "goodsImg": null,
    "goodsOrder": 99,
    "canteenNum": "SZ0003",
    "canteenName": "虎踞路食堂",
    "goodsType": "CPU",
    "extAttr1": "文字列表",
    "extAttr2": "20210517",
    "extAttr3": "午餐",
    "extAttr4": null,
    "extAttr": null,
    "goodsCategoryList": [
      {
        "goodsNum": "c5520",
        "goodsName": "水煮肉片",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c5373",
        "goodsName": "青椒土豆丝",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c5877",
        "goodsName": "香菇青菜",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "20000275",
        "goodsName": "侉芹炒百叶",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c4857",
        "goodsName": "清蒸小黄鱼",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c3884",
        "goodsName": "有机花菜肉片",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c4845",
        "goodsName": "玉米粒炒鸡丁",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "20000274",
        "goodsName": "红烧仔鸡",
        "goodsPrice": "7",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      },
      {
        "goodsNum": "c19057",
        "goodsName": "蒜苗炒香肠",
        "goodsPrice": "1",
        "goodsDesc": null,
        "goodsImg": null,
        "goodsOrder": 99,
        "canteenNum": "SZ0003",
        "canteenName": "虎踞路食堂",
        "goodsType": "CP",
        "extAttr1": null,
        "extAttr2": null,
        "extAttr3": null,
        "extAttr4": null,
        "extAttr": null,
        "goodsCategoryList": null
      }
    ]
  }
];


foodMenus.sort((m1, m2) => {
  if ((m1.extAttr3 == "早餐" && m2.extAttr3 == "午餐")
    || (m1.extAttr3 == "早餐" && m2.extAttr3 == "晚餐")
    || (m1.extAttr3 == "午餐" && m2.extAttr3 == "晚餐")) {
    return -1;
  } else {
    return 1;
  }
})

for (let menu of foodMenus) {
  console.log(menu.goodsName, menu.extAttr3);
}


